Repository Vasilii-Khusamov/WinFormsApp_Test2, pull requests merged in 2022-08, with the labels that each got.

#1 Добавлена фича вращения падающей фигуры
  Commands/RotateFallingShape.cs
  Extentions/TwoDimensionalArrayExtension.cs
  Program.cs
  Utils/BrickMapOperations.cs
Labels: enhancement

#2 Исправлена команда вращения фигуры
  Commands/RotateFallingShape.cs
  Utils/BrickMapOperations.cs
Labels: bug

#5 Добавлена возможность очищать линии
  Program.cs
  Rules/LineCleaningRule.cs
  Utils/BrickMapOperations.cs
Labels: enhancement

#6 Добавлена отрисовка очков
  MainForm.Designer.cs
  MainForm.cs
  Printers/ScorePrinter.cs
  Program.cs
  Rules/testRule.cs
Labels: enhancement

#4 Добавлена возможность скользить фигурой
  Commands/MoveDownFallingShape.cs
  GameState.cs
  Program.cs
  Rules/FallingShapeCollisionRule.cs
  Rules/FallingShapeRule.cs
Labels: enhancement

#7 релиз версии 1.0
  Commands/MoveDownFallingShape.cs
  Commands/RotateFallingShape.cs
  Extentions/TwoDimensionalArrayExtension.cs
  GameState.cs
  MainForm.Designer.cs
  MainForm.cs
  Printers/ScorePrinter.cs
  Program.cs
  Rules/FallingShapeCollisionRule.cs
  Rules/FallingShapeRule.cs
  Rules/LineCleaningRule.cs
  Rules/testRule.cs
  Utils/BrickMapOperations.cs
Labels: release

#10 Добавлен файл README
  MainForm.Designer.cs
  README.md
Labels: documentation

#12 #9 Добавил Game over
  Forms/GameOverForm.Designer.cs
  Forms/GameOverForm.cs
  Forms/GameOverForm.resx
  GameState.cs
  Printers/GameOverPrinter.cs
  Program.cs
  Rules/GameOverRule.cs
Labels: enhancement

#13 Версия 1.0.1
  Forms/GameOverForm.Designer.cs
  Forms/GameOverForm.cs
  Forms/GameOverForm.resx
  GameState.cs
  MainForm.Designer.cs
  Printers/GameOverPrinter.cs
  Program.cs
  README.md
  Rules/GameOverRule.cs
Labels: release

#14 Добавлена поддержка разных кистей
  GameData/BrickBrushPalette.cs
Labels: bug
